from django.urls import path,include
from . import views

urlpatterns = [
    path('login/',views.login_page,name="login"),
    path('register/',views.register_page,name="register"),
    path('dashboard/',views.dashboard_page,name="dashboard"),
    path('logout/',views.logout_page,name="logout"),
    path('instructor_dashboard/',views.instructor_dashboard_page,name="instructor_dashboard"),
    path('course/',views.course_page,name="course"),
    path('my_courses/',views.my_courses_page,name="my_courses"),
    path('assignment/',views.assignment_page,name="assignment"),
    path('create_assignment/',views.create_assignment_page,name="create_assignment"),
    path('questions/<int:quiz_id>/',views.questions_page,name="questions"),
    path('create_quiz/',views.create_quiz_page,name="create_quiz"),
    path('quiz/',views.quiz_page,name="quiz"),
    path('instructor_profile/',views.instructor_profile_page,name="instructor_profile"),
    path('available_courses/',views.available_courses_page,name="available_courses"),
    path('enrolled_courses/<int:course_id>/',views.enrolled_courses_page,name="enrolled_courses"),
    path('enrolled_courses/',views.enrolled_courses_page,name="enrolled_courses"),
    path('enrolled_button/<int:course_id>',views.enrolled_button,name="enrolled_button"),
    path('assignment_display_student/',views.assignment_display_student_page,name="assignment_display_student"),
    path('submit_assignment/<int:assignment_id>/',views.submit_assignment_page,name="submit_assignment"),
    path('quiz_display_student/',views.quiz_display_student_page,name="quiz_display_student"),
    path('take_quiz/<int:Quiz_id>/',views.take_quiz_page,name="take_quiz"),
    path('add_module/<int:course_id>/',views.add_module_page,name="add_module"),
    path('create_module_form/<int:course_id>/',views.create_module_form_page,name="create_module_form"),
    path('finish_course_setup/<int:course_id>/',views.finish_course_setup_page,name="finish_course_setup"),
    path('module_view_student/<int:course_id>/',views.module_view_student_page,name="module_view_student"),
    path('student_profile/',views.student_profile_page,name="student_profile"),
    path('edit_student_profile/',views.edit_student_profile_page,name="edit_student_profile"),
    path('student_certificates/',views.certificates_page,name="student_certificates"),
    path('download_certificate/<str:course_title>/',views.download_certificate_page,name="download_certificate"),
    path('forget_password/',views.forget_password_page,name="forget_password"),
    path('reset_password/<str:token>/',views.reset_password_page,name="reset_password"),
    path('edit_instructor_profile/',views.edit_instructor_profile_page,name="edit_instructor_profile"),
    path('edit_course/<int:course_id>/',views.edit_course_page,name="edit_course"),
    path('view_quiz/<int:quiz_id>/',views.view_quiz_page,name="view_quiz"),
    path( "edit-quiz/<int:quiz_id>/",views.edit_quiz_page,name="edit_quiz"),
    path("delete-quiz/<int:quiz_id>/",views.delete_quiz_page,name="delete_quiz"),
    path("view-assignment/<int:assignment_id>/",views.view_assignment_page,name="view_assignment"),
    path(  "edit-assignment/<int:assignment_id>/",views.edit_assignment_page,name="edit_assignment"),
    path("delete-assignment/<int:assignment_id>/",views.delete_assignment_page,name="delete_assignment"),
]