# Generated by Django 5.2.16 on 2026-08-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enrolled_courses_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitted_assignments_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file_url', models.URLField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.assignment_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register_tb')),
            ],
        ),
    ]
