# Generated by Django 5.2.16 on 2026-08-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_submitted_assignments_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='created_modules_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('module_title', models.CharField(max_length=500)),
                ('module_description', models.CharField(max_length=500)),
                ('pdf_url', models.URLField()),
                ('quiz_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
