# Generated by Django 5.2.16 on 2026-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_created_modules_model_course_is_setup_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='completed_quiz_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
